# functions/ops_console/main.py
#
# The Ops Console — fullstack web UI for the AI Ops platform, served entirely
# from ONE Lambda behind a (free) Lambda Function URL. No frameworks, no build
# step, stdlib + boto3 only: the zip stays tiny and cold starts stay ~100ms.
#
#   GET  /              -> single-page frontend (HTML below)
#   GET  /api/pending   -> executions waiting at the human approval gate,
#                          with the AI analysis AND the task token — so the
#                          browser's Approve/Reject buttons replace the CLI
#   POST /api/decide    -> {taskToken, approved} -> states:SendTaskSuccess
#   GET  /api/incidents -> recent workflow executions (history view)
#   POST /api/ask       -> proxies to the runbook assistant Lambda
#   GET  /api/costs     -> 7-day Cost Explorer summary (numbers only — the
#                          daily AI narrative stays with the cost_reporter)
#
# Auth: every /api route requires header `x-console-key` matching CONSOLE_KEY
# (random value generated by Terraform, stored in Secrets Manager). The login
# screen asks for it once. Honest trade-off for a portfolio project; the
# production path is Cognito/IAM auth on the Function URL — see README.
#
# How /api/pending finds task tokens: our state machine passes
# "taskToken.$": "$$.Task.Token" into the notify Lambda's payload, and Step
# Functions records that payload in the TaskScheduled event of the execution
# history. So for each RUNNING execution we read the history (newest first)
# and extract the token + analysis from the most recent TaskScheduled event.

import json
import logging
import os
from datetime import datetime, timedelta, timezone

import boto3

logger = logging.getLogger()
logger.setLevel(logging.INFO)

AWS_REGION         = os.environ.get("AWS_REGION_NAME", "us-east-1")
SFN_ARN            = os.environ.get("STATE_MACHINE_ARN", "")
RUNBOOK_LAMBDA_ARN = os.environ.get("RUNBOOK_LAMBDA_ARN", "")
CONSOLE_KEY        = os.environ.get("CONSOLE_KEY", "")
ENVIRONMENT        = os.environ.get("ENVIRONMENT", "dev")

sfn    = boto3.client("stepfunctions", region_name=AWS_REGION)
lam    = boto3.client("lambda", region_name=AWS_REGION)
ce     = boto3.client("ce", region_name="us-east-1")  # Cost Explorer is global


# ─── HELPERS ─────────────────────────────────────────────────────────────────

def resp(status: int, body, content_type="application/json") -> dict:
    return {
        "statusCode": status,
        "headers": {"Content-Type": content_type, "Cache-Control": "no-store"},
        "body": body if isinstance(body, str) else json.dumps(body, default=str),
    }


def authed(event: dict) -> bool:
    headers = {k.lower(): v for k, v in (event.get("headers") or {}).items()}
    return bool(CONSOLE_KEY) and headers.get("x-console-key") == CONSOLE_KEY


# ─── PENDING APPROVALS ───────────────────────────────────────────────────────

def get_pending() -> list:
    """RUNNING executions parked at the waitForTaskToken state, with the AI
    analysis and the task token extracted from execution history."""
    pending = []
    running = sfn.list_executions(
        stateMachineArn=SFN_ARN, statusFilter="RUNNING", maxResults=25
    ).get("executions", [])

    for ex in running:
        try:
            hist = sfn.get_execution_history(
                executionArn=ex["executionArn"], reverseOrder=True, maxResults=60
            ).get("events", [])
        except Exception as e:  # noqa: BLE001
            logger.warning(f"history read failed for {ex['name']}: {e}")
            continue

        for ev in hist:  # newest -> oldest
            if ev.get("type") != "TaskScheduled":
                continue
            params_raw = ev.get("taskScheduledEventDetails", {}).get("parameters", "")
            try:
                payload = json.loads(params_raw).get("Payload", {})
            except json.JSONDecodeError:
                continue
            token = payload.get("taskToken")
            if not token:
                continue  # that was the AI_Analysis invoke, not the wait state
            pending.append({
                "execution_name": ex["name"],
                "started": ex["startDate"],
                "task_token": token,
                "analysis": payload.get("analysis", {}),
                "alarm": payload.get("alarm", {}),
            })
            break  # most recent wait state found for this execution
    return pending


def decide(body: dict) -> dict:
    token    = body.get("taskToken", "")
    approved = bool(body.get("approved", False))
    if not token:
        return resp(400, {"error": "taskToken is required"})
    try:
        sfn.send_task_success(
            taskToken=token,
            output=json.dumps({"approved": approved, "via": "ops-console"}),
        )
        logger.info(f"decision sent: approved={approved}")
        return resp(200, {"ok": True, "approved": approved})
    except Exception as e:  # noqa: BLE001 — token expired / already used
        logger.error(f"send_task_success failed: {e}")
        return resp(409, {"error": f"Could not deliver decision: {e}"})


# ─── INCIDENT HISTORY ────────────────────────────────────────────────────────

def get_incidents() -> list:
    executions = sfn.list_executions(stateMachineArn=SFN_ARN, maxResults=25).get("executions", [])
    return [{
        "name": ex["name"],
        "status": ex["status"],
        "started": ex["startDate"],
        "stopped": ex.get("stopDate"),
    } for ex in executions]


# ─── RUNBOOK ASSISTANT PROXY ─────────────────────────────────────────────────

def ask(body: dict) -> dict:
    question = (body.get("question") or "").strip()
    if not question or len(question) > 2000:
        return resp(400, {"error": "question must be 1–2000 characters"})
    try:
        result = lam.invoke(
            FunctionName=RUNBOOK_LAMBDA_ARN,
            Payload=json.dumps({"question": question}).encode(),
        )
        payload = json.loads(result["Payload"].read())
        inner = json.loads(payload.get("body", "{}"))
        return resp(payload.get("statusCode", 200), inner)
    except Exception as e:  # noqa: BLE001
        logger.error(f"runbook invoke failed: {e}")
        return resp(503, {"error": "Runbook assistant unavailable"})


# ─── COSTS ───────────────────────────────────────────────────────────────────

def get_costs() -> dict:
    end   = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    start = (datetime.now(timezone.utc) - timedelta(days=7)).strftime("%Y-%m-%d")
    data = ce.get_cost_and_usage(
        TimePeriod={"Start": start, "End": end},
        Granularity="DAILY",
        Metrics=["UnblendedCost"],
        GroupBy=[{"Type": "DIMENSION", "Key": "SERVICE"}],
    )
    daily, services = {}, {}
    for day in data.get("ResultsByTime", []):
        date, total = day["TimePeriod"]["Start"], 0.0
        for g in day.get("Groups", []):
            amt = float(g["Metrics"]["UnblendedCost"]["Amount"])
            if amt > 0.001:
                total += amt
                services[g["Keys"][0]] = services.get(g["Keys"][0], 0.0) + amt
        daily[date] = round(total, 4)
    top = sorted(services.items(), key=lambda x: -x[1])[:6]
    return {
        "total_7d": round(sum(daily.values()), 2),
        "avg_daily": round(sum(daily.values()) / max(len(daily), 1), 2),
        "daily": daily,
        "top_services": [{"service": s, "cost": round(c, 2)} for s, c in top],
    }


# ─── HANDLER (Lambda Function URL, payload v2) ───────────────────────────────

def lambda_handler(event, context):
    method = event.get("requestContext", {}).get("http", {}).get("method", "GET")
    path   = event.get("rawPath", "/")

    if method == "GET" and path == "/":
        return resp(200, CONSOLE_HTML, content_type="text/html; charset=utf-8")

    if not path.startswith("/api/"):
        return resp(404, {"error": "not found"})
    if not authed(event):
        return resp(401, {"error": "invalid or missing x-console-key"})

    body = {}
    if event.get("body"):
        try:
            raw = event["body"]
            if event.get("isBase64Encoded"):
                import base64
                raw = base64.b64decode(raw).decode()
            body = json.loads(raw)
        except (json.JSONDecodeError, ValueError):
            return resp(400, {"error": "invalid JSON body"})

    try:
        if method == "GET" and path == "/api/pending":
            return resp(200, {"pending": get_pending(), "environment": ENVIRONMENT})
        if method == "POST" and path == "/api/decide":
            return decide(body)
        if method == "GET" and path == "/api/incidents":
            return resp(200, {"incidents": get_incidents()})
        if method == "POST" and path == "/api/ask":
            return ask(body)
        if method == "GET" and path == "/api/costs":
            return resp(200, get_costs())
        return resp(404, {"error": "not found"})
    except Exception as e:  # noqa: BLE001
        logger.error(f"unhandled: {e}", exc_info=True)
        return resp(500, {"error": "internal error"})


# ─── FRONTEND ────────────────────────────────────────────────────────────────
# Single file, no build step. Same visual family as the demo app: control-room
# monospace, dark slate, amber accent. Key is kept in sessionStorage.

CONSOLE_HTML = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AI Ops Console</title>
<style>
:root{--bg:#0f1416;--panel:#161d21;--line:#263036;--ink:#e6e1d4;--dim:#7f8a82;
      --amber:#d9a441;--ok:#7fb069;--bad:#e0693e;--blue:#6da3c0}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
*{box-sizing:border-box;margin:0}
body{background:var(--bg);color:var(--ink);min-height:100vh;
     font-family:"IBM Plex Mono",ui-monospace,Menlo,Consolas,monospace;font-size:14px}
header{display:flex;align-items:baseline;gap:14px;padding:20px 24px;border-bottom:1px solid var(--line)}
header h1{font-size:17px;font-weight:600}
header h1 em{font-style:normal;color:var(--amber)}
header .env{color:var(--dim);font-size:12px;letter-spacing:.14em;text-transform:uppercase}
nav{display:flex;gap:4px;padding:12px 24px 0}
nav button{font:inherit;font-size:13px;color:var(--dim);background:none;border:none;
           border-bottom:2px solid transparent;padding:8px 14px;cursor:pointer}
nav button.active{color:var(--ink);border-color:var(--amber)}
nav button:focus-visible{outline:2px solid var(--amber);outline-offset:2px}
main{padding:20px 24px;max-width:960px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:16px 18px;margin-bottom:12px}
.k{color:var(--dim);font-size:11px;letter-spacing:.12em;text-transform:uppercase}
.badge{display:inline-block;font-size:11px;padding:2px 8px;border-radius:20px;border:1px solid var(--line)}
.badge.RUNNING{color:var(--amber);border-color:#4a3d22}
.badge.SUCCEEDED{color:var(--ok);border-color:#2e4227}
.badge.FAILED,.badge.TIMED_OUT,.badge.ABORTED{color:var(--bad);border-color:#4a2c22}
.badge.HIGH,.badge.CRITICAL{color:var(--bad);border-color:#4a2c22}
.badge.MEDIUM{color:var(--amber);border-color:#4a3d22}
.badge.LOW{color:var(--ok);border-color:#2e4227}
button.act{font:inherit;font-size:13px;border-radius:8px;padding:9px 18px;cursor:pointer;
           background:transparent;border:1px solid var(--line);color:var(--ink)}
button.act:hover{border-color:var(--amber)}
button.act:focus-visible{outline:2px solid var(--amber);outline-offset:2px}
button.approve{color:var(--ok);border-color:#2e4227}
button.reject{color:var(--bad);border-color:#4a2c22}
.row{display:flex;gap:10px;flex-wrap:wrap;margin-top:12px}
.muted{color:var(--dim)}
.empty{color:var(--dim);padding:32px 0;text-align:center}
table{width:100%;border-collapse:collapse}
td,th{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line);font-size:13px}
th{color:var(--dim);font-weight:400;font-size:11px;letter-spacing:.12em;text-transform:uppercase}
td.num{text-align:right;font-variant-numeric:tabular-nums}
input,textarea{font:inherit;width:100%;background:var(--bg);color:var(--ink);
               border:1px solid var(--line);border-radius:8px;padding:10px 12px}
input:focus,textarea:focus{outline:2px solid var(--amber);outline-offset:1px}
#login{position:fixed;inset:0;background:var(--bg);display:grid;place-items:center;z-index:9}
#login .card{width:min(420px,92vw)}
.answer{white-space:pre-wrap;line-height:1.65;margin-top:12px}
.spin{color:var(--dim)}
h2{font-size:14px;font-weight:600;margin:4px 0 14px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px}
@media(max-width:640px){.grid2{grid-template-columns:1fr}}
</style>
</head>
<body>

<div id="login">
  <div class="card">
    <p class="k">ai ops console · authenticate</p>
    <h2 style="margin-top:8px">Enter the console key</h2>
    <p class="muted" style="font-size:12px;margin-bottom:12px">
      aws secretsmanager get-secret-value --secret-id &lt;project&gt;/&lt;env&gt;/ops-console/key
    </p>
    <input id="keyInput" type="password" placeholder="console key" autocomplete="off">
    <div class="row"><button class="act" onclick="saveKey()">Enter console</button></div>
    <p id="loginErr" class="muted" style="font-size:12px;margin-top:10px"></p>
  </div>
</div>

<header>
  <h1>AI Ops <em>/</em> Console</h1>
  <span class="env" id="envLabel"></span>
</header>

<nav>
  <button id="tab-pending" class="active" onclick="show('pending')">Approvals</button>
  <button id="tab-incidents" onclick="show('incidents')">Incidents</button>
  <button id="tab-ask" onclick="show('ask')">Assistant</button>
  <button id="tab-costs" onclick="show('costs')">Costs</button>
</nav>

<main>
  <section id="view-pending"><p class="spin">Loading…</p></section>
  <section id="view-incidents" hidden></section>
  <section id="view-ask" hidden>
    <div class="card">
      <p class="k">runbook assistant · answers from your s3 runbooks via bedrock</p>
      <div class="row" style="margin-top:10px">
        <textarea id="q" rows="2" placeholder="How do I roll back a failed deployment?"></textarea>
      </div>
      <div class="row"><button class="act" onclick="askQ()">Ask</button></div>
      <div id="answer" class="answer"></div>
    </div>
  </section>
  <section id="view-costs" hidden></section>
</main>

<script>
const KEY = () => sessionStorage.getItem('consoleKey') || '';
const api = (path, opts={}) => fetch(path, {...opts,
  headers:{'Content-Type':'application/json','x-console-key':KEY(), ...(opts.headers||{})}});

function saveKey(){
  sessionStorage.setItem('consoleKey', document.getElementById('keyInput').value.trim());
  api('/api/incidents').then(r=>{
    if(r.status===401){document.getElementById('loginErr').textContent='Key rejected — check Secrets Manager.';return;}
    document.getElementById('login').style.display='none'; loadAll();
  });
}
if(KEY()){document.getElementById('login').style.display='none'; loadAll();}

function show(name){
  for(const v of ['pending','incidents','ask','costs']){
    document.getElementById('view-'+v).hidden = v!==name;
    document.getElementById('tab-'+v).className = v===name?'active':'';
  }
}
function esc(s){const d=document.createElement('div');d.textContent=s==null?'':String(s);return d.innerHTML;}
function when(t){return t?new Date(t).toLocaleString():'—';}

async function loadPending(){
  const el=document.getElementById('view-pending');
  try{
    const r=await api('/api/pending'); const d=await r.json();
    document.getElementById('envLabel').textContent=(d.environment||'')+' · '+new Date().toLocaleTimeString();
    if(!d.pending || !d.pending.length){
      el.innerHTML='<p class="empty">No incidents waiting for approval. Quiet is good.</p>';return;}
    el.innerHTML=d.pending.map(p=>{
      const a=p.analysis||{};
      return `<div class="card">
        <p class="k">awaiting human approval · started ${esc(when(p.started))}</p>
        <h2>${esc(a.alarm_name||p.execution_name)}
          <span class="badge ${esc(a.urgency||'')}">${esc(a.urgency||'?')}</span></h2>
        <p><span class="k">summary</span><br>${esc(a.summary||'—')}</p>
        <p style="margin-top:8px"><span class="k">root cause</span><br>${esc(a.root_cause||'—')}</p>
        <p style="margin-top:8px"><span class="k">proposed action</span><br>
          <code>${esc(a.recommended_action||'log_only')}</code> on
          <code>${esc(a.resource||'n/a')}</code>
          <span class="muted">(target resolved by platform, not AI)</span></p>
        <div class="row">
          <button class="act approve" onclick="decide('${esc(p.task_token)}',true,this)">Approve — execute fix</button>
          <button class="act reject" onclick="decide('${esc(p.task_token)}',false,this)">Reject — no action</button>
        </div></div>`;
    }).join('');
  }catch(e){el.innerHTML='<p class="empty">Could not load approvals.</p>';}
}

async function decide(token,approved,btn){
  btn.disabled=true; btn.textContent=approved?'Approving…':'Rejecting…';
  const r=await api('/api/decide',{method:'POST',body:JSON.stringify({taskToken:token,approved})});
  if(r.ok){loadPending(); setTimeout(loadIncidents,1500);}
  else{const d=await r.json(); btn.disabled=false; btn.textContent='Failed — '+(d.error||r.status);}
}

async function loadIncidents(){
  const el=document.getElementById('view-incidents');
  try{
    const r=await api('/api/incidents'); const d=await r.json();
    if(!d.incidents||!d.incidents.length){el.innerHTML='<p class="empty">No workflow executions yet.</p>';return;}
    el.innerHTML=`<div class="card"><p class="k">last ${d.incidents.length} workflow executions</p>
      <table><tr><th>execution</th><th>status</th><th>started</th><th>ended</th></tr>`+
      d.incidents.map(i=>`<tr><td>${esc(i.name)}</td>
        <td><span class="badge ${esc(i.status)}">${esc(i.status)}</span></td>
        <td>${esc(when(i.started))}</td><td>${esc(when(i.stopped))}</td></tr>`).join('')+
      '</table></div>';
  }catch(e){el.innerHTML='<p class="empty">Could not load incidents.</p>';}
}

async function askQ(){
  const q=document.getElementById('q').value.trim(); if(!q)return;
  const out=document.getElementById('answer'); out.textContent='Thinking…';
  const r=await api('/api/ask',{method:'POST',body:JSON.stringify({question:q})});
  const d=await r.json();
  out.textContent = d.answer ? d.answer + (d.sources&&d.sources.length?'\\n\\n— sources: '+d.sources.join(', '):'')
                             : (d.error||'No answer.');
}

async function loadCosts(){
  const el=document.getElementById('view-costs');
  try{
    const r=await api('/api/costs'); const d=await r.json();
    const days=Object.entries(d.daily||{}).sort();
    const max=Math.max(...days.map(x=>x[1]),0.01);
    el.innerHTML=`<div class="grid2">
      <div class="card"><p class="k">7-day total</p><h2 style="font-size:26px">$${d.total_7d}</h2>
        <p class="muted">avg $${d.avg_daily}/day</p></div>
      <div class="card"><p class="k">top services</p><table>`+
        (d.top_services||[]).map(s=>`<tr><td>${esc(s.service)}</td><td class="num">$${s.cost}</td></tr>`).join('')+
      `</table></div></div>
      <div class="card"><p class="k">daily spend</p><table>`+
        days.map(([dt,v])=>`<tr><td>${esc(dt)}</td><td class="num">$${v.toFixed(2)}</td>
          <td style="width:45%"><div style="height:8px;border-radius:4px;background:var(--amber);opacity:.85;width:${Math.max(2,(v/max*100)).toFixed(0)}%"></div></td></tr>`).join('')+
      '</table><p class="muted" style="margin-top:10px;font-size:12px">Numbers only — the daily AI narrative arrives via the cost reporter in Slack/email.</p></div>';
  }catch(e){el.innerHTML='<p class="empty">Could not load costs.</p>';}
}

function loadAll(){loadPending();loadIncidents();loadCosts();setInterval(loadPending,15000);}
</script>
</body>
</html>"""